# How to Read HTML Data:

In [36]:
import pandas as pd

In [37]:
data=pd.read_html('https://www.espncricinfo.com/rankings/content/page/211271.html')

In [38]:
pd.set_option('display.max_row',None)

In [39]:
data

[   Pos          Team  Matches  Points  Rating
 0    1     Australia       25    3102     124
 1    2         India       29    3318     114
 2    3  South Africa       25    2606     104
 3    4       England       43    4449     103
 4    5   New Zealand       27    2704     100
 5    6      Pakistan       23    2126      92
 6    7     Sri Lanka       26    2282      88
 7    8   West Indies       28    2198      79
 8    9    Bangladesh       22    1047      48
 9   10      Zimbabwe        6     148      25,
     Pos          Team  Matches  Points  Rating
 0     1   New Zealand       23    2670     116
 1     2       England       30    3400     113
 2     3     Australia       32    3572     112
 3     4         India       38    4098     108
 4     5      Pakistan       21    2237     107
 5     6  South Africa       24    2392     100
 6     7    Bangladesh       33    3129      95
 7     8     Sri Lanka       31    2800      90
 8     9   Afghanistan       20    1419      71
 9    10   West Indies       41    2902      71
 10   11       Ireland       23    1214      53
 11   12      Scotland       31    1459      47
 12   13      Zimbabwe       26    1098      42
 13   14       Namibia       26     971      37
 14   15   Netherlands       21     673      32
 15   16          Oman       30     919      31
 16   17           UAE       25     693      28
 17   18           USA       31     821      26
 18   19         Nepal       28     456      16
 19   20           PNG       30     128       4,
     Pos            Team  Matches  Points  Rating
 0     1           India       63   16881     268
 1     2         England       49   13029     266
 2     3        Pakistan       55   14168     258
 3     4    South Africa       41   10510     256
 4     5     New Zealand       50   12621     252
 5     6       Australia       47   11784     251
 6     7     West Indies       51   12039     236
 7     8       Sri Lanka       50   11732     235
 8     9      Bangladesh       51   11328     222
 9    10     Afghanistan       30    6512     217
 10   11        Zimbabwe       46    8976     195
 11   12         Ireland       54   10282     190
 12   13             UAE       29    5298     183
 13   14         Namibia       32    5846     183
 14   15        Scotland       24    4373     182
 15   16           Nepal       30    5387     180
 16   17     Netherlands       32    5668     177
 17   18            Oman       26    4090     157
 18   19             PNG       24    3495     146
 19   20          Canada       24    3297     137
 20   21       Hong Kong       20    2555     128
 21   22          Jersey       23    2924     127
 22   23           Qatar       13    1643     126
 23   24          Uganda       36    4359     121
 24   25          Kuwait       18    2153     120
 25   26             USA       16    1908     119
 26   27       Singapore       21    2416     115
 27   28        Malaysia       28    2979     106
 28   29           Kenya       31    3272     106
 29   30        Tanzania       26    2645     102
 30   31         Bahrain       23    2291     100
 31   32           Italy       19    1818      96
 32   33    Saudi Arabia       13    1234      95
 33   34         Germany       34    2996      88
 34   35         Bermuda       12    1053      88
 35   36           Spain       21    1705      81
 36   37         Denmark       21    1518      72
 37   38        Guernsey       17    1194      70
 38   39     Isle of Man       10     678      68
 39   40         Belgium       20    1349      67
 40   41         Nigeria       29    1952      67
 41   42  Cayman Islands        8     529      66
 42   43         Austria       26    1686      65
 43   44         Vanuatu       11     645      59
 44   45        Portugal       11     644      59
 45   46         Romania       24    1359      57
 46   47        Botswana       18     992      55
 47   48          Norway       17     897      53
 48   49         Finland       17     892      52
 49   50          France        9     470      52
 50   51       Argentina        9     435      48
 51   52          Malawi       17     818      48
 52   53          Sweden       16     690      43
 53   54    Cook Islands        6     245      41
 54   55  Czech Republic       28    1137      41
 55   56       Indonesia        7     265      38
 56   57     Switzerland       11     396      36
 57   58           Malta       33    1179      36
 58   59           Ghana       23     813      35
 59   60    Sierra Leone       17     586      34
 60   61           Japan        7     236      34
 61   62      Luxembourg       23     774      34
 62   63      Mozambique       23     721      31
 63   64          Bhutan        8     239      30
 64   65            Fiji        6     177      30
 65   66          Rwanda       22     609      28
 66   67          Cyprus       11     283      26
 67   68         Bahamas       11     260      24
 68   69         Hungary       16     358      22
 69   70          Belize        6     132      22
 70   71          Panama        6     125      21
 71   72          Serbia       17     184      11
 72   73        Bulgaria       34     296       9
 73   74          Gambia        7      50       7
 74   75         Lesotho       12      82       7
 75   76        Maldives       15      81       5
 76   77           Samoa        8      42       5
 77   78       Gibraltar       21      68       3
 78   79          Greece        9      27       3
 79   80          Turkey        6       0       0
 80   81        Thailand       10       0       0
 81   82        Eswatini       18       0       0
 82   83      Seychelles       10       0       0
 83   84         Estonia       12       0       0
 84   85        Cameroon       13       0       0,
     Pos                Team  Matches  Points  Rating
 0     1     Australia Women       18    3061     170
 1     2       England Women       28    3342     119
 2     3  South Africa Women       26    3098     119
 3     4         India Women       27    2820     104
 4     5   New Zealand Women       25    2553     102
 5     6   West Indies Women       27    2535      94
 6     7    Bangladesh Women       13     983      76
 7     8      Thailand Women        8     572      72
 8     9      Pakistan Women       24    1519      63
 9    10     Sri Lanka Women        8     353      44
 10   11       Ireland Women       14     548      39
 11   12   Netherlands Women        9       0       0
 12   13      Zimbabwe Women        8       0       0,
     Pos                Team  Matches  Points  Rating
 0     1     Australia Women       19    5615     296
 1     2       England Women       26    7320     282
 2     3   New Zealand Women       24    6509     271
 3     4         India Women       34    9084     267
 4     5  South Africa Women       17    7121     246
 5     6   West Indies Women       15    3503     234
 6     7      Pakistan Women       24    5339     222
 7     8     Sri Lanka Women       23    4804     209
 8     9    Bangladesh Women       22    4205     191
 9    10       Ireland Women       22    3953     180
 10   11      Zimbabwe Women       20    3239     162
 11   12      Thailand Women       22    3557     162
 12   13           PNG Women       10    1558     156
 13   14      Scotland Women       15    2142     143
 14   15           UAE Women       31    4093     132
 15   16      Tanzania Women       12    1487     124
 16   17         Nepal Women       19    2093     110
 17   18       Namibia Women       21    2189     104
 18   19     Indonesia Women        8     826     103
 19   20   Netherlands Women       13    1302     100
 20   21        Uganda Women       22    2057      94
 21   22     Hong Kong Women       18    1523      85
 22   23         Kenya Women       18    1502      83
 23   24        Jersey Women        6     458      76
 24   25           USA Women       14     971      69
 25   26         Italy Women       12     721      60
 26   27        Rwanda Women       19    1126      59
 27   28      Malaysia Women       24    1403      58
 28   29       Nigeria Women       18     947      53
 29   30        Sweden Women       10     495      50
 30   31       Germany Women       20     952      47
 31   32        Brazil Women       19     900      47
 32   33        Canada Women        6     277      46
 33   34        Belize Women        3     135      45
 34   35         Spain Women        8     256      32
 35   36    Mozambique Women       12     328      27
 36   37  Sierra Leone Women        7     173      25
 37   38        France Women        9     214      24
 38   39      Botswana Women       15     345      23
 39   40        Bhutan Women        9     207      23
 40   41          Oman Women       13     289      22
 41   42        Malawi Women        4      71      18
 42   43        Kuwait Women       16     278      17
 43   44       Bahrain Women        8     138      17
 44   45         Qatar Women       14     218      16
 45   46       Romania Women        7     105      15
 46   47    Costa Rica Women        3      34      11
 47   48     Argentina Women       12      95       8
 48   49       Austria Women       16      99       6
 49   50      Eswatini Women        9       0       0
 50   51     Singapore Women       13       0       0
 51   52        Norway Women        9       0       0
 52   53          Peru Women        5       0       0]

In [40]:
type(data)

list

In [41]:
data[0]

   Pos          Team  Matches  Points  Rating
0    1     Australia       25    3102     124
1    2         India       29    3318     114
2    3  South Africa       25    2606     104
3    4       England       43    4449     103
4    5   New Zealand       27    2704     100
5    6      Pakistan       23    2126      92
6    7     Sri Lanka       26    2282      88
7    8   West Indies       28    2198      79
8    9    Bangladesh       22    1047      48
9   10      Zimbabwe        6     148      25

In [42]:
data[1]

    Pos          Team  Matches  Points  Rating
0     1   New Zealand       23    2670     116
1     2       England       30    3400     113
2     3     Australia       32    3572     112
3     4         India       38    4098     108
4     5      Pakistan       21    2237     107
5     6  South Africa       24    2392     100
6     7    Bangladesh       33    3129      95
7     8     Sri Lanka       31    2800      90
8     9   Afghanistan       20    1419      71
9    10   West Indies       41    2902      71
10   11       Ireland       23    1214      53
11   12      Scotland       31    1459      47
12   13      Zimbabwe       26    1098      42
13   14       Namibia       26     971      37
14   15   Netherlands       21     673      32
15   16          Oman       30     919      31
16   17           UAE       25     693      28
17   18           USA       31     821      26
18   19         Nepal       28     456      16
19   20           PNG       30     128       4

# Add Data

In [43]:
df=pd.DataFrame()
for i in range(len(data)):
    df=df.append(data[i])

In [44]:
df

    Pos                Team  Matches  Points  Rating
0     1           Australia       25    3102     124
1     2               India       29    3318     114
2     3        South Africa       25    2606     104
3     4             England       43    4449     103
4     5         New Zealand       27    2704     100
5     6            Pakistan       23    2126      92
6     7           Sri Lanka       26    2282      88
7     8         West Indies       28    2198      79
8     9          Bangladesh       22    1047      48
9    10            Zimbabwe        6     148      25
0     1         New Zealand       23    2670     116
1     2             England       30    3400     113
2     3           Australia       32    3572     112
3     4               India       38    4098     108
4     5            Pakistan       21    2237     107
5     6        South Africa       24    2392     100
6     7          Bangladesh       33    3129      95
7     8           Sri Lanka       31    2800      90
8     9         Afghanistan       20    1419      71
9    10         West Indies       41    2902      71
10   11             Ireland       23    1214      53
11   12            Scotland       31    1459      47
12   13            Zimbabwe       26    1098      42
13   14             Namibia       26     971      37
14   15         Netherlands       21     673      32
15   16                Oman       30     919      31
16   17                 UAE       25     693      28
17   18                 USA       31     821      26
18   19               Nepal       28     456      16
19   20                 PNG       30     128       4
0     1               India       63   16881     268
1     2             England       49   13029     266
2     3            Pakistan       55   14168     258
3     4        South Africa       41   10510     256
4     5         New Zealand       50   12621     252
5     6           Australia       47   11784     251
6     7         West Indies       51   12039     236
7     8           Sri Lanka       50   11732     235
8     9          Bangladesh       51   11328     222
9    10         Afghanistan       30    6512     217
10   11            Zimbabwe       46    8976     195
11   12             Ireland       54   10282     190
12   13                 UAE       29    5298     183
13   14             Namibia       32    5846     183
14   15            Scotland       24    4373     182
15   16               Nepal       30    5387     180
16   17         Netherlands       32    5668     177
17   18                Oman       26    4090     157
18   19                 PNG       24    3495     146
19   20              Canada       24    3297     137
20   21           Hong Kong       20    2555     128
21   22              Jersey       23    2924     127
22   23               Qatar       13    1643     126
23   24              Uganda       36    4359     121
24   25              Kuwait       18    2153     120
25   26                 USA       16    1908     119
26   27           Singapore       21    2416     115
27   28            Malaysia       28    2979     106
28   29               Kenya       31    3272     106
29   30            Tanzania       26    2645     102
30   31             Bahrain       23    2291     100
31   32               Italy       19    1818      96
32   33        Saudi Arabia       13    1234      95
33   34             Germany       34    2996      88
34   35             Bermuda       12    1053      88
35   36               Spain       21    1705      81
36   37             Denmark       21    1518      72
37   38            Guernsey       17    1194      70
38   39         Isle of Man       10     678      68
39   40             Belgium       20    1349      67
40   41             Nigeria       29    1952      67
41   42      Cayman Islands        8     529      66
42   43             Austria       26    1686      65
43   44             Vanuatu       11     645      59
44   45            Portugal       11     644      59
45   46             Romania       24    1359      57
46   47            Botswana       18     992      55
47   48              Norway       17     897      53
48   49             Finland       17     892      52
49   50              France        9     470      52
50   51           Argentina        9     435      48
51   52              Malawi       17     818      48
52   53              Sweden       16     690      43
53   54        Cook Islands        6     245      41
54   55      Czech Republic       28    1137      41
55   56           Indonesia        7     265      38
56   57         Switzerland       11     396      36
57   58               Malta       33    1179      36
58   59               Ghana       23     813      35
59   60        Sierra Leone       17     586      34
60   61               Japan        7     236      34
61   62          Luxembourg       23     774      34
62   63          Mozambique       23     721      31
63   64              Bhutan        8     239      30
64   65                Fiji        6     177      30
65   66              Rwanda       22     609      28
66   67              Cyprus       11     283      26
67   68             Bahamas       11     260      24
68   69             Hungary       16     358      22
69   70              Belize        6     132      22
70   71              Panama        6     125      21
71   72              Serbia       17     184      11
72   73            Bulgaria       34     296       9
73   74              Gambia        7      50       7
74   75             Lesotho       12      82       7
75   76            Maldives       15      81       5
76   77               Samoa        8      42       5
77   78           Gibraltar       21      68       3
78   79              Greece        9      27       3
79   80              Turkey        6       0       0
80   81            Thailand       10       0       0
81   82            Eswatini       18       0       0
82   83          Seychelles       10       0       0
83   84             Estonia       12       0       0
84   85            Cameroon       13       0       0
0     1     Australia Women       18    3061     170
1     2       England Women       28    3342     119
2     3  South Africa Women       26    3098     119
3     4         India Women       27    2820     104
4     5   New Zealand Women       25    2553     102
5     6   West Indies Women       27    2535      94
6     7    Bangladesh Women       13     983      76
7     8      Thailand Women        8     572      72
8     9      Pakistan Women       24    1519      63
9    10     Sri Lanka Women        8     353      44
10   11       Ireland Women       14     548      39
11   12   Netherlands Women        9       0       0
12   13      Zimbabwe Women        8       0       0
0     1     Australia Women       19    5615     296
1     2       England Women       26    7320     282
2     3   New Zealand Women       24    6509     271
3     4         India Women       34    9084     267
4     5  South Africa Women       17    7121     246
5     6   West Indies Women       15    3503     234
6     7      Pakistan Women       24    5339     222
7     8     Sri Lanka Women       23    4804     209
8     9    Bangladesh Women       22    4205     191
9    10       Ireland Women       22    3953     180
10   11      Zimbabwe Women       20    3239     162
11   12      Thailand Women       22    3557     162
12   13           PNG Women       10    1558     156
13   14      Scotland Women       15    2142     143
14   15           UAE Women       31    4093     132
15   16      Tanzania Women       12    1487     124
16   17         Nepal Women       19    2093     110
17   18       Namibia Women       21    2189     104
18   19     Indonesia Women        8     826     103
19   20   Netherlands Women       13    1302     100
20   21        Uganda Women       22    2057      94
21   22     Hong Kong Women       18    1523      85
22   23         Kenya Women       18    1502      83
23   24        Jersey Women        6     458      76
24   25           USA Women       14     971      69
25   26         Italy Women       12     721      60
26   27        Rwanda Women       19    1126      59
27   28      Malaysia Women       24    1403      58
28   29       Nigeria Women       18     947      53
29   30        Sweden Women       10     495      50
30   31       Germany Women       20     952      47
31   32        Brazil Women       19     900      47
32   33        Canada Women        6     277      46
33   34        Belize Women        3     135      45
34   35         Spain Women        8     256      32
35   36    Mozambique Women       12     328      27
36   37  Sierra Leone Women        7     173      25
37   38        France Women        9     214      24
38   39      Botswana Women       15     345      23
39   40        Bhutan Women        9     207      23
40   41          Oman Women       13     289      22
41   42        Malawi Women        4      71      18
42   43        Kuwait Women       16     278      17
43   44       Bahrain Women        8     138      17
44   45         Qatar Women       14     218      16
45   46       Romania Women        7     105      15
46   47    Costa Rica Women        3      34      11
47   48     Argentina Women       12      95       8
48   49       Austria Women       16      99       6
49   50      Eswatini Women        9       0       0
50   51     Singapore Women       13       0       0
51   52        Norway Women        9       0       0
52   53          Peru Women        5       0       0

In [45]:
df.shape

(181, 5)

# Indexing Serial wise

In [46]:
df.index=range(181)

In [47]:
df

     Pos                Team  Matches  Points  Rating
0      1           Australia       25    3102     124
1      2               India       29    3318     114
2      3        South Africa       25    2606     104
3      4             England       43    4449     103
4      5         New Zealand       27    2704     100
5      6            Pakistan       23    2126      92
6      7           Sri Lanka       26    2282      88
7      8         West Indies       28    2198      79
8      9          Bangladesh       22    1047      48
9     10            Zimbabwe        6     148      25
10     1         New Zealand       23    2670     116
11     2             England       30    3400     113
12     3           Australia       32    3572     112
13     4               India       38    4098     108
14     5            Pakistan       21    2237     107
15     6        South Africa       24    2392     100
16     7          Bangladesh       33    3129      95
17     8           Sri Lanka       31    2800      90
18     9         Afghanistan       20    1419      71
19    10         West Indies       41    2902      71
20    11             Ireland       23    1214      53
21    12            Scotland       31    1459      47
22    13            Zimbabwe       26    1098      42
23    14             Namibia       26     971      37
24    15         Netherlands       21     673      32
25    16                Oman       30     919      31
26    17                 UAE       25     693      28
27    18                 USA       31     821      26
28    19               Nepal       28     456      16
29    20                 PNG       30     128       4
30     1               India       63   16881     268
31     2             England       49   13029     266
32     3            Pakistan       55   14168     258
33     4        South Africa       41   10510     256
34     5         New Zealand       50   12621     252
35     6           Australia       47   11784     251
36     7         West Indies       51   12039     236
37     8           Sri Lanka       50   11732     235
38     9          Bangladesh       51   11328     222
39    10         Afghanistan       30    6512     217
40    11            Zimbabwe       46    8976     195
41    12             Ireland       54   10282     190
42    13                 UAE       29    5298     183
43    14             Namibia       32    5846     183
44    15            Scotland       24    4373     182
45    16               Nepal       30    5387     180
46    17         Netherlands       32    5668     177
47    18                Oman       26    4090     157
48    19                 PNG       24    3495     146
49    20              Canada       24    3297     137
50    21           Hong Kong       20    2555     128
51    22              Jersey       23    2924     127
52    23               Qatar       13    1643     126
53    24              Uganda       36    4359     121
54    25              Kuwait       18    2153     120
55    26                 USA       16    1908     119
56    27           Singapore       21    2416     115
57    28            Malaysia       28    2979     106
58    29               Kenya       31    3272     106
59    30            Tanzania       26    2645     102
60    31             Bahrain       23    2291     100
61    32               Italy       19    1818      96
62    33        Saudi Arabia       13    1234      95
63    34             Germany       34    2996      88
64    35             Bermuda       12    1053      88
65    36               Spain       21    1705      81
66    37             Denmark       21    1518      72
67    38            Guernsey       17    1194      70
68    39         Isle of Man       10     678      68
69    40             Belgium       20    1349      67
70    41             Nigeria       29    1952      67
71    42      Cayman Islands        8     529      66
72    43             Austria       26    1686      65
73    44             Vanuatu       11     645      59
74    45            Portugal       11     644      59
75    46             Romania       24    1359      57
76    47            Botswana       18     992      55
77    48              Norway       17     897      53
78    49             Finland       17     892      52
79    50              France        9     470      52
80    51           Argentina        9     435      48
81    52              Malawi       17     818      48
82    53              Sweden       16     690      43
83    54        Cook Islands        6     245      41
84    55      Czech Republic       28    1137      41
85    56           Indonesia        7     265      38
86    57         Switzerland       11     396      36
87    58               Malta       33    1179      36
88    59               Ghana       23     813      35
89    60        Sierra Leone       17     586      34
90    61               Japan        7     236      34
91    62          Luxembourg       23     774      34
92    63          Mozambique       23     721      31
93    64              Bhutan        8     239      30
94    65                Fiji        6     177      30
95    66              Rwanda       22     609      28
96    67              Cyprus       11     283      26
97    68             Bahamas       11     260      24
98    69             Hungary       16     358      22
99    70              Belize        6     132      22
100   71              Panama        6     125      21
101   72              Serbia       17     184      11
102   73            Bulgaria       34     296       9
103   74              Gambia        7      50       7
104   75             Lesotho       12      82       7
105   76            Maldives       15      81       5
106   77               Samoa        8      42       5
107   78           Gibraltar       21      68       3
108   79              Greece        9      27       3
109   80              Turkey        6       0       0
110   81            Thailand       10       0       0
111   82            Eswatini       18       0       0
112   83          Seychelles       10       0       0
113   84             Estonia       12       0       0
114   85            Cameroon       13       0       0
115    1     Australia Women       18    3061     170
116    2       England Women       28    3342     119
117    3  South Africa Women       26    3098     119
118    4         India Women       27    2820     104
119    5   New Zealand Women       25    2553     102
120    6   West Indies Women       27    2535      94
121    7    Bangladesh Women       13     983      76
122    8      Thailand Women        8     572      72
123    9      Pakistan Women       24    1519      63
124   10     Sri Lanka Women        8     353      44
125   11       Ireland Women       14     548      39
126   12   Netherlands Women        9       0       0
127   13      Zimbabwe Women        8       0       0
128    1     Australia Women       19    5615     296
129    2       England Women       26    7320     282
130    3   New Zealand Women       24    6509     271
131    4         India Women       34    9084     267
132    5  South Africa Women       17    7121     246
133    6   West Indies Women       15    3503     234
134    7      Pakistan Women       24    5339     222
135    8     Sri Lanka Women       23    4804     209
136    9    Bangladesh Women       22    4205     191
137   10       Ireland Women       22    3953     180
138   11      Zimbabwe Women       20    3239     162
139   12      Thailand Women       22    3557     162
140   13           PNG Women       10    1558     156
141   14      Scotland Women       15    2142     143
142   15           UAE Women       31    4093     132
143   16      Tanzania Women       12    1487     124
144   17         Nepal Women       19    2093     110
145   18       Namibia Women       21    2189     104
146   19     Indonesia Women        8     826     103
147   20   Netherlands Women       13    1302     100
148   21        Uganda Women       22    2057      94
149   22     Hong Kong Women       18    1523      85
150   23         Kenya Women       18    1502      83
151   24        Jersey Women        6     458      76
152   25           USA Women       14     971      69
153   26         Italy Women       12     721      60
154   27        Rwanda Women       19    1126      59
155   28      Malaysia Women       24    1403      58
156   29       Nigeria Women       18     947      53
157   30        Sweden Women       10     495      50
158   31       Germany Women       20     952      47
159   32        Brazil Women       19     900      47
160   33        Canada Women        6     277      46
161   34        Belize Women        3     135      45
162   35         Spain Women        8     256      32
163   36    Mozambique Women       12     328      27
164   37  Sierra Leone Women        7     173      25
165   38        France Women        9     214      24
166   39      Botswana Women       15     345      23
167   40        Bhutan Women        9     207      23
168   41          Oman Women       13     289      22
169   42        Malawi Women        4      71      18
170   43        Kuwait Women       16     278      17
171   44       Bahrain Women        8     138      17
172   45         Qatar Women       14     218      16
173   46       Romania Women        7     105      15
174   47    Costa Rica Women        3      34      11
175   48     Argentina Women       12      95       8
176   49       Austria Women       16      99       6
177   50      Eswatini Women        9       0       0
178   51     Singapore Women       13       0       0
179   52        Norway Women        9       0       0
180   53          Peru Women        5       0       0

# Serial wise pos

In [52]:
df.Pos=range(1,182)

In [53]:
df

     Pos                Team  Matches  Points  Rating
0      1           Australia       25    3102     124
1      2               India       29    3318     114
2      3        South Africa       25    2606     104
3      4             England       43    4449     103
4      5         New Zealand       27    2704     100
5      6            Pakistan       23    2126      92
6      7           Sri Lanka       26    2282      88
7      8         West Indies       28    2198      79
8      9          Bangladesh       22    1047      48
9     10            Zimbabwe        6     148      25
10    11         New Zealand       23    2670     116
11    12             England       30    3400     113
12    13           Australia       32    3572     112
13    14               India       38    4098     108
14    15            Pakistan       21    2237     107
15    16        South Africa       24    2392     100
16    17          Bangladesh       33    3129      95
17    18           Sri Lanka       31    2800      90
18    19         Afghanistan       20    1419      71
19    20         West Indies       41    2902      71
20    21             Ireland       23    1214      53
21    22            Scotland       31    1459      47
22    23            Zimbabwe       26    1098      42
23    24             Namibia       26     971      37
24    25         Netherlands       21     673      32
25    26                Oman       30     919      31
26    27                 UAE       25     693      28
27    28                 USA       31     821      26
28    29               Nepal       28     456      16
29    30                 PNG       30     128       4
30    31               India       63   16881     268
31    32             England       49   13029     266
32    33            Pakistan       55   14168     258
33    34        South Africa       41   10510     256
34    35         New Zealand       50   12621     252
35    36           Australia       47   11784     251
36    37         West Indies       51   12039     236
37    38           Sri Lanka       50   11732     235
38    39          Bangladesh       51   11328     222
39    40         Afghanistan       30    6512     217
40    41            Zimbabwe       46    8976     195
41    42             Ireland       54   10282     190
42    43                 UAE       29    5298     183
43    44             Namibia       32    5846     183
44    45            Scotland       24    4373     182
45    46               Nepal       30    5387     180
46    47         Netherlands       32    5668     177
47    48                Oman       26    4090     157
48    49                 PNG       24    3495     146
49    50              Canada       24    3297     137
50    51           Hong Kong       20    2555     128
51    52              Jersey       23    2924     127
52    53               Qatar       13    1643     126
53    54              Uganda       36    4359     121
54    55              Kuwait       18    2153     120
55    56                 USA       16    1908     119
56    57           Singapore       21    2416     115
57    58            Malaysia       28    2979     106
58    59               Kenya       31    3272     106
59    60            Tanzania       26    2645     102
60    61             Bahrain       23    2291     100
61    62               Italy       19    1818      96
62    63        Saudi Arabia       13    1234      95
63    64             Germany       34    2996      88
64    65             Bermuda       12    1053      88
65    66               Spain       21    1705      81
66    67             Denmark       21    1518      72
67    68            Guernsey       17    1194      70
68    69         Isle of Man       10     678      68
69    70             Belgium       20    1349      67
70    71             Nigeria       29    1952      67
71    72      Cayman Islands        8     529      66
72    73             Austria       26    1686      65
73    74             Vanuatu       11     645      59
74    75            Portugal       11     644      59
75    76             Romania       24    1359      57
76    77            Botswana       18     992      55
77    78              Norway       17     897      53
78    79             Finland       17     892      52
79    80              France        9     470      52
80    81           Argentina        9     435      48
81    82              Malawi       17     818      48
82    83              Sweden       16     690      43
83    84        Cook Islands        6     245      41
84    85      Czech Republic       28    1137      41
85    86           Indonesia        7     265      38
86    87         Switzerland       11     396      36
87    88               Malta       33    1179      36
88    89               Ghana       23     813      35
89    90        Sierra Leone       17     586      34
90    91               Japan        7     236      34
91    92          Luxembourg       23     774      34
92    93          Mozambique       23     721      31
93    94              Bhutan        8     239      30
94    95                Fiji        6     177      30
95    96              Rwanda       22     609      28
96    97              Cyprus       11     283      26
97    98             Bahamas       11     260      24
98    99             Hungary       16     358      22
99   100              Belize        6     132      22
100  101              Panama        6     125      21
101  102              Serbia       17     184      11
102  103            Bulgaria       34     296       9
103  104              Gambia        7      50       7
104  105             Lesotho       12      82       7
105  106            Maldives       15      81       5
106  107               Samoa        8      42       5
107  108           Gibraltar       21      68       3
108  109              Greece        9      27       3
109  110              Turkey        6       0       0
110  111            Thailand       10       0       0
111  112            Eswatini       18       0       0
112  113          Seychelles       10       0       0
113  114             Estonia       12       0       0
114  115            Cameroon       13       0       0
115  116     Australia Women       18    3061     170
116  117       England Women       28    3342     119
117  118  South Africa Women       26    3098     119
118  119         India Women       27    2820     104
119  120   New Zealand Women       25    2553     102
120  121   West Indies Women       27    2535      94
121  122    Bangladesh Women       13     983      76
122  123      Thailand Women        8     572      72
123  124      Pakistan Women       24    1519      63
124  125     Sri Lanka Women        8     353      44
125  126       Ireland Women       14     548      39
126  127   Netherlands Women        9       0       0
127  128      Zimbabwe Women        8       0       0
128  129     Australia Women       19    5615     296
129  130       England Women       26    7320     282
130  131   New Zealand Women       24    6509     271
131  132         India Women       34    9084     267
132  133  South Africa Women       17    7121     246
133  134   West Indies Women       15    3503     234
134  135      Pakistan Women       24    5339     222
135  136     Sri Lanka Women       23    4804     209
136  137    Bangladesh Women       22    4205     191
137  138       Ireland Women       22    3953     180
138  139      Zimbabwe Women       20    3239     162
139  140      Thailand Women       22    3557     162
140  141           PNG Women       10    1558     156
141  142      Scotland Women       15    2142     143
142  143           UAE Women       31    4093     132
143  144      Tanzania Women       12    1487     124
144  145         Nepal Women       19    2093     110
145  146       Namibia Women       21    2189     104
146  147     Indonesia Women        8     826     103
147  148   Netherlands Women       13    1302     100
148  149        Uganda Women       22    2057      94
149  150     Hong Kong Women       18    1523      85
150  151         Kenya Women       18    1502      83
151  152        Jersey Women        6     458      76
152  153           USA Women       14     971      69
153  154         Italy Women       12     721      60
154  155        Rwanda Women       19    1126      59
155  156      Malaysia Women       24    1403      58
156  157       Nigeria Women       18     947      53
157  158        Sweden Women       10     495      50
158  159       Germany Women       20     952      47
159  160        Brazil Women       19     900      47
160  161        Canada Women        6     277      46
161  162        Belize Women        3     135      45
162  163         Spain Women        8     256      32
163  164    Mozambique Women       12     328      27
164  165  Sierra Leone Women        7     173      25
165  166        France Women        9     214      24
166  167      Botswana Women       15     345      23
167  168        Bhutan Women        9     207      23
168  169          Oman Women       13     289      22
169  170        Malawi Women        4      71      18
170  171        Kuwait Women       16     278      17
171  172       Bahrain Women        8     138      17
172  173         Qatar Women       14     218      16
173  174       Romania Women        7     105      15
174  175    Costa Rica Women        3      34      11
175  176     Argentina Women       12      95       8
176  177       Austria Women       16      99       6
177  178      Eswatini Women        9       0       0
178  179     Singapore Women       13       0       0
179  180        Norway Women        9       0       0
180  181          Peru Women        5       0       0

# (Set Index) change Column into index

In [54]:
df=df.set_index('Pos')

In [55]:
df

                   Team  Matches  Points  Rating
Pos
1             Australia       25    3102     124
2                 India       29    3318     114
3          South Africa       25    2606     104
4               England       43    4449     103
5           New Zealand       27    2704     100
6              Pakistan       23    2126      92
7             Sri Lanka       26    2282      88
8           West Indies       28    2198      79
9            Bangladesh       22    1047      48
10             Zimbabwe        6     148      25
11          New Zealand       23    2670     116
12              England       30    3400     113
13            Australia       32    3572     112
14                India       38    4098     108
15             Pakistan       21    2237     107
16         South Africa       24    2392     100
17           Bangladesh       33    3129      95
18            Sri Lanka       31    2800      90
19          Afghanistan       20    1419      71
20          West Indies       41    2902      71
21              Ireland       23    1214      53
22             Scotland       31    1459      47
23             Zimbabwe       26    1098      42
24              Namibia       26     971      37
25          Netherlands       21     673      32
26                 Oman       30     919      31
27                  UAE       25     693      28
28                  USA       31     821      26
29                Nepal       28     456      16
30                  PNG       30     128       4
31                India       63   16881     268
32              England       49   13029     266
33             Pakistan       55   14168     258
34         South Africa       41   10510     256
35          New Zealand       50   12621     252
36            Australia       47   11784     251
37          West Indies       51   12039     236
38            Sri Lanka       50   11732     235
39           Bangladesh       51   11328     222
40          Afghanistan       30    6512     217
41             Zimbabwe       46    8976     195
42              Ireland       54   10282     190
43                  UAE       29    5298     183
44              Namibia       32    5846     183
45             Scotland       24    4373     182
46                Nepal       30    5387     180
47          Netherlands       32    5668     177
48                 Oman       26    4090     157
49                  PNG       24    3495     146
50               Canada       24    3297     137
51            Hong Kong       20    2555     128
52               Jersey       23    2924     127
53                Qatar       13    1643     126
54               Uganda       36    4359     121
55               Kuwait       18    2153     120
56                  USA       16    1908     119
57            Singapore       21    2416     115
58             Malaysia       28    2979     106
59                Kenya       31    3272     106
60             Tanzania       26    2645     102
61              Bahrain       23    2291     100
62                Italy       19    1818      96
63         Saudi Arabia       13    1234      95
64              Germany       34    2996      88
65              Bermuda       12    1053      88
66                Spain       21    1705      81
67              Denmark       21    1518      72
68             Guernsey       17    1194      70
69          Isle of Man       10     678      68
70              Belgium       20    1349      67
71              Nigeria       29    1952      67
72       Cayman Islands        8     529      66
73              Austria       26    1686      65
74              Vanuatu       11     645      59
75             Portugal       11     644      59
76              Romania       24    1359      57
77             Botswana       18     992      55
78               Norway       17     897      53
79              Finland       17     892      52
80               France        9     470      52
81            Argentina        9     435      48
82               Malawi       17     818      48
83               Sweden       16     690      43
84         Cook Islands        6     245      41
85       Czech Republic       28    1137      41
86            Indonesia        7     265      38
87          Switzerland       11     396      36
88                Malta       33    1179      36
89                Ghana       23     813      35
90         Sierra Leone       17     586      34
91                Japan        7     236      34
92           Luxembourg       23     774      34
93           Mozambique       23     721      31
94               Bhutan        8     239      30
95                 Fiji        6     177      30
96               Rwanda       22     609      28
97               Cyprus       11     283      26
98              Bahamas       11     260      24
99              Hungary       16     358      22
100              Belize        6     132      22
101              Panama        6     125      21
102              Serbia       17     184      11
103            Bulgaria       34     296       9
104              Gambia        7      50       7
105             Lesotho       12      82       7
106            Maldives       15      81       5
107               Samoa        8      42       5
108           Gibraltar       21      68       3
109              Greece        9      27       3
110              Turkey        6       0       0
111            Thailand       10       0       0
112            Eswatini       18       0       0
113          Seychelles       10       0       0
114             Estonia       12       0       0
115            Cameroon       13       0       0
116     Australia Women       18    3061     170
117       England Women       28    3342     119
118  South Africa Women       26    3098     119
119         India Women       27    2820     104
120   New Zealand Women       25    2553     102
121   West Indies Women       27    2535      94
122    Bangladesh Women       13     983      76
123      Thailand Women        8     572      72
124      Pakistan Women       24    1519      63
125     Sri Lanka Women        8     353      44
126       Ireland Women       14     548      39
127   Netherlands Women        9       0       0
128      Zimbabwe Women        8       0       0
129     Australia Women       19    5615     296
130       England Women       26    7320     282
131   New Zealand Women       24    6509     271
132         India Women       34    9084     267
133  South Africa Women       17    7121     246
134   West Indies Women       15    3503     234
135      Pakistan Women       24    5339     222
136     Sri Lanka Women       23    4804     209
137    Bangladesh Women       22    4205     191
138       Ireland Women       22    3953     180
139      Zimbabwe Women       20    3239     162
140      Thailand Women       22    3557     162
141           PNG Women       10    1558     156
142      Scotland Women       15    2142     143
143           UAE Women       31    4093     132
144      Tanzania Women       12    1487     124
145         Nepal Women       19    2093     110
146       Namibia Women       21    2189     104
147     Indonesia Women        8     826     103
148   Netherlands Women       13    1302     100
149        Uganda Women       22    2057      94
150     Hong Kong Women       18    1523      85
151         Kenya Women       18    1502      83
152        Jersey Women        6     458      76
153           USA Women       14     971      69
154         Italy Women       12     721      60
155        Rwanda Women       19    1126      59
156      Malaysia Women       24    1403      58
157       Nigeria Women       18     947      53
158        Sweden Women       10     495      50
159       Germany Women       20     952      47
160        Brazil Women       19     900      47
161        Canada Women        6     277      46
162        Belize Women        3     135      45
163         Spain Women        8     256      32
164    Mozambique Women       12     328      27
165  Sierra Leone Women        7     173      25
166        France Women        9     214      24
167      Botswana Women       15     345      23
168        Bhutan Women        9     207      23
169          Oman Women       13     289      22
170        Malawi Women        4      71      18
171        Kuwait Women       16     278      17
172       Bahrain Women        8     138      17
173         Qatar Women       14     218      16
174       Romania Women        7     105      15
175    Costa Rica Women        3      34      11
176     Argentina Women       12      95       8
177       Austria Women       16      99       6
178      Eswatini Women        9       0       0
179     Singapore Women       13       0       0
180        Norway Women        9       0       0
181          Peru Women        5       0       0

In [56]:
df.to_csv('htmlfile.csv')